parameters:
#    mumecsapi.example.class: MUMECS\APIBundle\Example

services:
#    mumecsapi.example:
#        class: %mumecsapi.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    wsse.security.authentication.provider:
        class:  MUMECS\APIBundle\Security\Authentication\Provider\WsseProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces", 300]

    wsse.security.authentication.listener:
        class:  MUMECS\APIBundle\Security\Firewall\WsseListener
        arguments: ["@security.context", "@security.authentication.manager"]
