security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        MUMECS\StoreBundle\Document\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        #ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        user:
            mongodb: { class: MUMECS\StoreBundle\Document\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        wsse_secured:
            pattern:   /api/.*
            stateless: true
            wsse:      { lifetime: 30 }
            
        frontend:
            pattern:                            ^/*
            provider:                           user
            anonymous:                          ~
            form_login:
                login_path:                     mumecs_frontend_user_login
                #use_forward:                    false
                check_path:                     mumecs_frontend_user_login_check
                post_only:                      true
                always_use_default_target_path: false
                #default_target_path:            LEFrontendBundle_panel_personal
                target_path_parameter:          _target_path
                use_referer:                    true
                #success_handler:  ac_frontend.handler.login_success_handler
                failure_path:                   mumecs_frontend_user_login
            logout:
                path:                           mumecs_frontend_user_logout
            remember_me:
                key:                            MUM3CSs4pb3
                lifetime:                       3600

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
