parameters:
#    mumecs_backend.example.class: MUMECS\BackendBundle\Example

services:
#    mumecs_backend.example:
#        class: %mumecs_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
