parameters:
#    mumecs_store.example.class: MUMECS\StoreBundle\Example

services:
#    mumecs_store.example:
#        class: %mumecs_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]